name: Run Tests on Dockerized Selenium Grid

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-grid-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Selenium Hub
        run: |
          docker-compose -f ./src/test/resources/Docker-resources/selenium-grid-hub-and-nodes.yaml up -d

      - name: Run Tests
        run: |
          mvn clean test

      - name: Clean up Docker containers
        run: |
          docker-compose -f ./src/test/resources/Docker-resources/selenium-grid-hub-and-nodes.yaml down